language: node_js
node_js:
  - '6'
sudo: false
branches:
  only:
    - master
script:
    - npm run test-cov
after_script: 
  - npm install coveralls && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
  - npm run build:gh-pages
  - cd gh-pages/
  - git init
  - git config user.name xuexb
  - git config user.email fe.xiaowu@gmail.com
  - git add .
  - git status
  - git commit -m "build gh-pages"
  - git push --force --quiet "https://${GH_TOKEN}@github.com/zbfe/zui.git" master:gh-pages